const countryData = [
    { name: "Afghanistan", prefix: "+93", flag: "🇦🇫" },
    { name: "Åland Islands", prefix: "+358", flag: "🇦🇽" },
    { name: "Albania", prefix: "+355", flag: "🇦🇱" },
    { name: "Algeria", prefix: "+213", flag: "🇩🇿" },
    { name: "American Samoa", prefix: "+1", flag: "🇦🇸" },
    { name: "Andorra", prefix: "+376", flag: "🇦🇩" },
    { name: "Angola", prefix: "+244", flag: "🇦🇴" },
    { name: "Anguilla", prefix: "+1", flag: "🇦🇮" },
    { name: "Antigua and Barbuda", prefix: "+1", flag: "🇦🇬" },
    { name: "Argentina", prefix: "+54", flag: "🇦🇷" },
    { name: "Armenia", prefix: "+374", flag: "🇦🇲" },
    { name: "Aruba", prefix: "+297", flag: "🇦🇼" },
    { name: "Australia", prefix: "+61", flag: "🇦🇺" },
    { name: "Austria", prefix: "+43", flag: "🇦🇹" },
    { name: "Azerbaijan", prefix: "+994", flag: "🇦🇿" },
    { name: "Bahamas", prefix: "+1", flag: "🇧🇸" },
    { name: "Bahrain", prefix: "+973", flag: "🇧🇭" },
    { name: "Bangladesh", prefix: "+880", flag: "🇧🇩" },
    { name: "Barbados", prefix: "+1", flag: "🇧🇧" },
    { name: "Belarus", prefix: "+375", flag: "🇧🇾" },
    { name: "Belgium", prefix: "+32", flag: "🇧🇪" },
    { name: "Belize", prefix: "+501", flag: "🇧🇿" },
    { name: "Benin", prefix: "+229", flag: "🇧🇯" },
    { name: "Bermuda", prefix: "+1", flag: "🇧🇲" },
    { name: "Bhutan", prefix: "+975", flag: "🇧🇹" },
    { name: "Bolivia", prefix: "+591", flag: "🇧🇴" },
    { name: "Bosnia and Herzegovina", prefix: "+387", flag: "🇧🇦" },
    { name: "Botswana", prefix: "+267", flag: "🇧🇼" },
    { name: "Bouvet Island", prefix: "+47", flag: "🇧🇻" },
    { name: "Brazil", prefix: "+55", flag: "🇧🇷" },
    { name: "British Indian Ocean Territory", prefix: "+246", flag: "🇮🇴" },
    { name: "British Virgin Islands", prefix: "+1", flag: "🇻🇬" },
    { name: "Brunei", prefix: "+673", flag: "🇧🇳" },
    { name: "Bulgaria", prefix: "+359", flag: "🇧🇬" },
    { name: "Burkina Faso", prefix: "+226", flag: "🇧🇫" },
    { name: "Burundi", prefix: "+257", flag: "🇧🇮" },
    { name: "Cambodia", prefix: "+855", flag: "🇰🇭" },
    { name: "Cameroon", prefix: "+237", flag: "🇨🇲" },
    { name: "Canada", prefix: "+1", flag: "🇨🇦" },
    { name: "Cape Verde", prefix: "+238", flag: "🇨🇻" },
    { name: "Caribbean Netherlands", prefix: "+599", flag: "🇧🇶" },
    { name: "Cayman Islands", prefix: "+1", flag: "🇰🇾" },
    { name: "Central African Republic", prefix: "+236", flag: "🇨🇫" },
    { name: "Chad", prefix: "+235", flag: "🇹🇩" },
    { name: "Chile", prefix: "+56", flag: "🇨🇱" },
    { name: "China", prefix: "+86", flag: "🇨🇳" },
    { name: "Christmas Island", prefix: "+61", flag: "🇨🇽" },
    { name: "Cocos (Keeling) Islands", prefix: "+61", flag: "🇨🇨" },
    { name: "Colombia", prefix: "+57", flag: "🇨🇴" },
    { name: "Comoros", prefix: "+269", flag: "🇰🇲" },
    { name: "Cook Islands", prefix: "+682", flag: "🇨🇰" },
    { name: "Costa Rica", prefix: "+506", flag: "🇨🇷" },
    { name: "Croatia", prefix: "+385", flag: "🇭🇷" },
    { name: "Cuba", prefix: "+53", flag: "🇨🇺" },
    { name: "Curaçao", prefix: "+599", flag: "🇨🇼" },
    { name: "Cyprus", prefix: "+357", flag: "🇨🇾" },
    { name: "Czechia", prefix: "+420", flag: "🇨🇿" },
    { name: "Denmark", prefix: "+45", flag: "🇩🇰" },
    { name: "Djibouti", prefix: "+253", flag: "🇩🇯" },
    { name: "Dominica", prefix: "+1", flag: "🇩🇲" },
    { name: "Dominican Republic", prefix: "+1", flag: "🇩🇴" },
    { name: "DR Congo", prefix: "+243", flag: "🇨🇩" },
    { name: "Ecuador", prefix: "+593", flag: "🇪🇨" },
    { name: "Egypt", prefix: "+20", flag: "🇪🇬" },
    { name: "El Salvador", prefix: "+503", flag: "🇸🇻" },
    { name: "Equatorial Guinea", prefix: "+240", flag: "🇬🇶" },
    { name: "Eritrea", prefix: "+291", flag: "🇪🇷" },
    { name: "Estonia", prefix: "+372", flag: "🇪🇪" },
    { name: "Eswatini", prefix: "+268", flag: "🇸🇿" },
    { name: "Ethiopia", prefix: "+251", flag: "🇪🇹" },
    { name: "Falkland Islands", prefix: "+500", flag: "🇫🇰" },
    { name: "Faroe Islands", prefix: "+298", flag: "🇫🇴" },
    { name: "Fiji", prefix: "+679", flag: "🇫🇯" },
    { name: "Finland", prefix: "+358", flag: "🇫🇮" },
    { name: "France", prefix: "+33", flag: "🇫🇷" },
    { name: "French Guiana", prefix: "+594", flag: "🇬🇫" },
    { name: "French Polynesia", prefix: "+689", flag: "🇵🇫" },
    { name: "French Southern and Antarctic Lands", prefix: "+262", flag: "🇹🇫" },
    { name: "Gabon", prefix: "+241", flag: "🇬🇦" },
    { name: "Gambia", prefix: "+220", flag: "🇬🇲" },
    { name: "Georgia", prefix: "+995", flag: "🇬🇪" },
    { name: "Germany", prefix: "+49", flag: "🇩🇪" },
    { name: "Ghana", prefix: "+233", flag: "🇬🇭" },
    { name: "Gibraltar", prefix: "+350", flag: "🇬🇮" },
    { name: "Greece", prefix: "+30", flag: "🇬🇷" },
    { name: "Greenland", prefix: "+299", flag: "🇬🇱" },
    { name: "Grenada", prefix: "+1", flag: "🇬🇩" },
    { name: "Guadeloupe", prefix: "+590", flag: "🇬🇵" },
    { name: "Guam", prefix: "+1", flag: "🇬🇺" },
    { name: "Guatemala", prefix: "+502", flag: "🇬🇹" },
    { name: "Guernsey", prefix: "+44", flag: "🇬🇬" },
    { name: "Guinea", prefix: "+224", flag: "🇬🇳" },
    { name: "Guinea-Bissau", prefix: "+245", flag: "🇬🇼" },
    { name: "Guyana", prefix: "+592", flag: "🇬🇾" },
    { name: "Haiti", prefix: "+509", flag: "🇭🇹" },
    { name: "Honduras", prefix: "+504", flag: "🇭🇳" },
    { name: "Hong Kong", prefix: "+852", flag: "🇭🇰" },
    { name: "Hungary", prefix: "+36", flag: "🇭🇺" },
    { name: "Iceland", prefix: "+354", flag: "🇮🇸" },
    { name: "India", prefix: "+91", flag: "🇮🇳" },
    { name: "Indonesia", prefix: "+62", flag: "🇮🇩" },
    { name: "Iran", prefix: "+98", flag: "🇮🇷" },
    { name: "Iraq", prefix: "+964", flag: "🇮🇶" },
    { name: "Ireland", prefix: "+353", flag: "🇮🇪" },
    { name: "Isle of Man", prefix: "+44", flag: "🇮🇲" },
    { name: "Israel", prefix: "+972", flag: "🇮🇱" },
    { name: "Italy", prefix: "+39", flag: "🇮🇹" },
    { name: "Ivory Coast", prefix: "+225", flag: "🇨🇮" },
    { name: "Jamaica", prefix: "+1", flag: "🇯🇲" },
    { name: "Japan", prefix: "+81", flag: "🇯🇵" },
    { name: "Jersey", prefix: "+44", flag: "🇯🇪" },
    { name: "Jordan", prefix: "+962", flag: "🇯🇴" },
    { name: "Kazakhstan", prefix: "+7", flag: "🇰🇿" },
    { name: "Kenya", prefix: "+254", flag: "🇰🇪" },
    { name: "Kiribati", prefix: "+686", flag: "🇰🇮" },
    { name: "Kosovo", prefix: "+383", flag: "🇽🇰" },
    { name: "Kuwait", prefix: "+965", flag: "🇰🇼" },
    { name: "Kyrgyzstan", prefix: "+996", flag: "🇰🇬" },
    { name: "Laos", prefix: "+856", flag: "🇱🇦" },
    { name: "Latvia", prefix: "+371", flag: "🇱🇻" },
    { name: "Lebanon", prefix: "+961", flag: "🇱🇧" },
    { name: "Lesotho", prefix: "+266", flag: "🇱🇸" },
    { name: "Liberia", prefix: "+231", flag: "🇱🇷" },
    { name: "Libya", prefix: "+218", flag: "🇱🇾" },
    { name: "Liechtenstein", prefix: "+423", flag: "🇱🇮" },
    { name: "Lithuania", prefix: "+370", flag: "🇱🇹" },
    { name: "Luxembourg", prefix: "+352", flag: "🇱🇺" },
    { name: "Macau", prefix: "+853", flag: "🇲🇴" },
    { name: "Madagascar", prefix: "+261", flag: "🇲🇬" },
    { name: "Malawi", prefix: "+265", flag: "🇲🇼" },
    { name: "Malaysia", prefix: "+60", flag: "🇲🇾" },
    { name: "Maldives", prefix: "+960", flag: "🇲🇻" },
    { name: "Mali", prefix: "+223", flag: "🇲🇱" },
    { name: "Malta", prefix: "+356", flag: "🇲🇹" },
    { name: "Marshall Islands", prefix: "+692", flag: "🇲🇭" },
    { name: "Martinique", prefix: "+596", flag: "🇲🇶" },
    { name: "Mauritania", prefix: "+222", flag: "🇲🇷" },
    { name: "Mauritius", prefix: "+230", flag: "🇲🇺" },
    { name: "Mayotte", prefix: "+262", flag: "🇾🇹" },
    { name: "Mexico", prefix: "+52", flag: "🇲🇽" },
    { name: "Micronesia", prefix: "+691", flag: "🇫🇲" },
    { name: "Moldova", prefix: "+373", flag: "🇲🇩" },
    { name: "Monaco", prefix: "+377", flag: "🇲🇨" },
    { name: "Mongolia", prefix: "+976", flag: "🇲🇳" },
    { name: "Montenegro", prefix: "+382", flag: "🇲🇪" },
    { name: "Montserrat", prefix: "+1", flag: "🇲🇸" },
    { name: "Morocco", prefix: "+212", flag: "🇲🇦" },
    { name: "Mozambique", prefix: "+258", flag: "🇲🇿" },
    { name: "Myanmar", prefix: "+95", flag: "🇲🇲" },
    { name: "Namibia", prefix: "+264", flag: "🇳🇦" },
    { name: "Nauru", prefix: "+674", flag: "🇳🇷" },
    { name: "Nepal", prefix: "+977", flag: "🇳🇵" },
    { name: "Netherlands", prefix: "+31", flag: "🇳🇱" },
    { name: "New Caledonia", prefix: "+687", flag: "🇳🇨" },
    { name: "New Zealand", prefix: "+64", flag: "🇳🇿" },
    { name: "Nicaragua", prefix: "+505", flag: "🇳🇮" },
    { name: "Niger", prefix: "+227", flag: "🇳🇪" },
    { name: "Nigeria", prefix: "+234", flag: "🇳🇬" },
    { name: "Niue", prefix: "+683", flag: "🇳🇺" },
    { name: "Norfolk Island", prefix: "+672", flag: "🇳🇫" },
    { name: "North Korea", prefix: "+850", flag: "🇰🇵" },
    { name: "North Macedonia", prefix: "+389", flag: "🇲🇰" },
    { name: "Northern Mariana Islands", prefix: "+1", flag: "🇲🇵" },
    { name: "Norway", prefix: "+47", flag: "🇳🇴" },
    { name: "Oman", prefix: "+968", flag: "🇴🇲" },
    { name: "Pakistan", prefix: "+92", flag: "🇵🇰" },
    { name: "Palau", prefix: "+680", flag: "🇵🇼" },
    { name: "Palestine", prefix: "+970", flag: "🇵🇸" },
    { name: "Panama", prefix: "+507", flag: "🇵🇦" },
    { name: "Papua New Guinea", prefix: "+675", flag: "🇵🇬" },
    { name: "Paraguay", prefix: "+595", flag: "🇵🇾" },
    { name: "Peru", prefix: "+51", flag: "🇵🇪" },
    { name: "Philippines", prefix: "+63", flag: "🇵🇭" },
    { name: "Pitcairn Islands", prefix: "+64", flag: "🇵🇳" },
    { name: "Poland", prefix: "+48", flag: "🇵🇱" },
    { name: "Portugal", prefix: "+351", flag: "🇵🇹" },
    { name: "Puerto Rico", prefix: "+1", flag: "🇵🇷" },
    { name: "Qatar", prefix: "+974", flag: "🇶🇦" },
    { name: "Republic of the Congo", prefix: "+242", flag: "🇨🇬" },
    { name: "Réunion", prefix: "+262", flag: "🇷🇪" },
    { name: "Romania", prefix: "+40", flag: "🇷🇴" },
    { name: "Russia", prefix: "+7", flag: "🇷🇺" },
    { name: "Rwanda", prefix: "+250", flag: "🇷🇼" },
    { name: "Saint Barthélemy", prefix: "+590", flag: "🇧🇱" },
    { name: "Saint Helena, Ascension and Tristan da Cunha", prefix: "+290", flag: "🇸🇭" },
    { name: "Saint Kitts and Nevis", prefix: "+1", flag: "🇰🇳" },
    { name: "Saint Lucia", prefix: "+1", flag: "🇱🇨" },
    { name: "Saint Martin", prefix: "+590", flag: "🇲🇫" },
    { name: "Saint Pierre and Miquelon", prefix: "+508", flag: "🇵🇲" },
    { name: "Saint Vincent and the Grenadines", prefix: "+1", flag: "🇻🇨" },
    { name: "Samoa", prefix: "+685", flag: "🇼🇸" },
    { name: "San Marino", prefix: "+378", flag: "🇸🇲" },
    { name: "São Tomé and Príncipe", prefix: "+239", flag: "🇸🇹" },
    { name: "Saudi Arabia", prefix: "+966", flag: "🇸🇦" },
    { name: "Senegal", prefix: "+221", flag: "🇸🇳" },
    { name: "Serbia", prefix: "+381", flag: "🇷🇸" },
    { name: "Seychelles", prefix: "+248", flag: "🇸🇨" },
    { name: "Sierra Leone", prefix: "+232", flag: "🇸🇱" },
    { name: "Singapore", prefix: "+65", flag: "🇸🇬" },
    { name: "Sint Maarten", prefix: "+1", flag: "🇸🇽" },
    { name: "Slovakia", prefix: "+421", flag: "🇸🇰" },
    { name: "Slovenia", prefix: "+386", flag: "🇸🇮" },
    { name: "Solomon Islands", prefix: "+677", flag: "🇸🇧" },
    { name: "Somalia", prefix: "+252", flag: "🇸🇴" },
    { name: "South Africa", prefix: "+27", flag: "🇿🇦" },
    { name: "South Georgia", prefix: "+500", flag: "🇬🇸" },
    { name: "South Korea", prefix: "+82", flag: "🇰🇷" },
    { name: "South Sudan", prefix: "+211", flag: "🇸🇸" },
    { name: "Spain", prefix: "+34", flag: "🇪🇸" },
    { name: "Sri Lanka", prefix: "+94", flag: "🇱🇰" },
    { name: "Sudan", prefix: "+249", flag: "🇸🇩" },
    { name: "Suriname", prefix: "+597", flag: "🇸🇷" },
    { name: "Svalbard and Jan Mayen", prefix: "+47", flag: "🇸🇯" },
    { name: "Sweden", prefix: "+46", flag: "🇸🇪" },
    { name: "Switzerland", prefix: "+41", flag: "🇨🇭" },
    { name: "Syria", prefix: "+963", flag: "🇸🇾" },
    { name: "Taiwan", prefix: "+886", flag: "🇹🇼" },
    { name: "Tajikistan", prefix: "+992", flag: "🇹🇯" },
    { name: "Tanzania", prefix: "+255", flag: "🇹🇿" },
    { name: "Thailand", prefix: "+66", flag: "🇹🇭" },
    { name: "Timor-Leste", prefix: "+670", flag: "🇹🇱" },
    { name: "Togo", prefix: "+228", flag: "🇹🇬" },
    { name: "Tokelau", prefix: "+690", flag: "🇹🇰" },
    { name: "Tonga", prefix: "+676", flag: "🇹🇴" },
    { name: "Trinidad and Tobago", prefix: "+1", flag: "🇹🇹" },
    { name: "Tunisia", prefix: "+216", flag: "🇹🇳" },
    { name: "Turkey", prefix: "+90", flag: "🇹🇷" },
    { name: "Turkmenistan", prefix: "+993", flag: "🇹🇲" },
    { name: "Turks and Caicos Islands", prefix: "+1", flag: "🇹🇨" },
    { name: "Tuvalu", prefix: "+688", flag: "🇹🇻" },
    { name: "Uganda", prefix: "+256", flag: "🇺🇬" },
    { name: "Ukraine", prefix: "+380", flag: "🇺🇦" },
    { name: "United Arab Emirates", prefix: "+971", flag: "🇦🇪" },
    { name: "United Kingdom", prefix: "+44", flag: "🇬🇧" },
    { name: "United States", prefix: "+1", flag: "🇺🇸" },
    { name: "United States Minor Outlying Islands", prefix: "+268", flag: "🇺🇲" },
    { name: "United States Virgin Islands", prefix: "+1", flag: "🇻🇮" },
    { name: "Uruguay", prefix: "+598", flag: "🇺🇾" },
    { name: "Uzbekistan", prefix: "+998", flag: "🇺🇿" },
    { name: "Vanuatu", prefix: "+678", flag: "🇻🇺" },
    { name: "Vatican City", prefix: "+379", flag: "🇻🇦" },
    { name: "Venezuela", prefix: "+58", flag: "🇻🇪" },
    { name: "Vietnam", prefix: "+84", flag: "🇻🇳" },
    { name: "Wallis and Futuna", prefix: "+681", flag: "🇼🇫" },
    { name: "Western Sahara", prefix: "+212", flag: "🇪🇭" },
    { name: "Yemen", prefix: "+967", flag: "🇾🇪" },
    { name: "Zambia", prefix: "+260", flag: "🇿🇲" },
    { name: "Zimbabwe", prefix: "+263", flag: "🇿🇼" },
]

export default countryData
